apiVersion: v1
kind: Secret
stringData:
  password: (GIT_PASSWORD)
  username: (GIT_USER_NAME)
metadata:
  annotations:
    tekton.dev/git-0: https://github.com
  labels:
    serviceAccount: pipeline
  name: git-secret
type: kubernetes.io/basic-auth
