apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
  annotations:
    tekton.dev/docker-0:  image-registry.openshift-image-registry.svc:5000
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: (TOKEN_TO_LOGIN_TO_OPENSHIFT_CLUSTER)




