apiVersion: v1
kind: Secret
stringData:
  password: c944dd3ff96f19065ff6d8ec9089636fd4021b7e
  username: imandi
metadata:
  annotations:
    tekton.dev/git-0: https://github.ibm.com
  labels:
    serviceAccount: pipeline
  name: git-secret
type: kubernetes.io/basic-auth
