apiVersion: v1
kind: Secret
metadata:
  name: common-services
data:
  username: YWRtaW4K
  password: YWRtaW4K
  url: aWNwLWNvbnNvbGUuY3A0aTIwMjAtZTQ3MGY4NzVkYjZkMjhjNDJjNmY4NGM4MTIzMDc0MjItMDAwMC51cy1lYXN0LmNvbnRhaW5lcnMuYXBwZG9tYWluLmNsb3VkCg==
  cloudType: aWJtY2xvdWQK
---
apiVersion: v1
data:
  password: Yzk0NGRkM2ZmOTZmMTkwNjVmZjZkOGVjOTA4OTYzNmZkNDAyMWI3ZQo=
  username: aW1hbmRpCg==
kind: Secret
metadata:
  annotations:
    tekton.dev/git-0: https://github.ibm.com
  labels:
    serviceAccount: pipeline
  name: git-secret
type: kubernetes.io/basic-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
  annotations:
    tekton.dev/docker-0:  image-registry.openshift-image-registry.svc:5000 # Described below
type: kubernetes.io/basic-auth
stringData:
  username: IAM#indcld9@us.ibm.com
  password: LmKPn_FtbR5NZpuiC2vDi1S1nWqpHxSCCSSN_TcNGkY
