apiVersion: v1
kind: PersistentVolume
metadata:
  name: ace-deploy
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /data/ace1
    server: 172.18.4.119
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs