apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: cp4i-ace-server-image
spec:
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/ace/cp4i-ace-server-bar
  type: image


