apiVersion: v1
kind: Secret
stringData:
  password: c0deshar3
  username: pimandi@hotmail.com
metadata:
  annotations:
    tekton.dev/git-0: https://github.com
  labels:
    serviceAccount: pipeline
  name: git-secret
type: kubernetes.io/basic-auth
